///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                     ShaderGsOutput.hlsl                                               //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

char* ShaderGsOutput =

"struct DXR_INPUT\n"
"{\n"
"    float3 Pos      : POSITION;\n"
"    float3 Nor      : NORMAL;\n"
"    float2 Tex0     : TEXCOORD0;\n"
"    float2 Tex1     : TEXCOORD1;\n"
"};\n"
//**************************************前がVS*************************************************//
"[maxvertexcount(3)]\n"
"void GS_Before_vs(triangle GS_Mesh_INPUT Input[3], inout TriangleStream <DXR_INPUT> triStream)\n"
"{\n"
"	DXR_INPUT p = (DXR_INPUT)0;\n"

"   p.Pos = Input[0].Pos.xyz;\n"
"   p.Nor = Input[0].Nor;\n"
"   p.Tex0 = Input[0].Tex0;\n"
"   p.Tex1 = Input[0].Tex1;\n"
"   triStream.Append(p);\n"
"   p.Pos = Input[1].Pos.xyz;\n"
"   p.Nor = Input[1].Nor;\n"
"   p.Tex0 = Input[1].Tex0;\n"
"   p.Tex1 = Input[1].Tex1;\n"
"   triStream.Append(p);\n"
"   p.Pos = Input[2].Pos.xyz;\n"
"   p.Nor = Input[2].Nor;\n"
"   p.Tex0 = Input[2].Tex0;\n"
"   p.Tex1 = Input[2].Tex1;\n"
"   triStream.Append(p);\n"
"	triStream.RestartStrip();\n"
"}\n"
//**************************************前がVS*************************************************//
"struct Normal3\n"
"{\n"
"    float3 nor0  : NORMAL0;\n"
"    float3 nor1  : NORMAL1;\n"
"    float3 nor2  : NORMAL2;\n"
"};\n"
"Normal3 NormalRecalculation(GS_Mesh_INPUT Input[3])\n"
"{\n"
//DSで頂点移動後の法線再計算
"   float3 vecX = Input[0].Pos.xyz - Input[1].Pos.xyz;\n"
"   float3 vecY = Input[0].Pos.xyz - Input[2].Pos.xyz;\n"
"   float3 vecNor = cross(vecX, vecY);\n"
"   Normal3 nor3;\n"
"   nor3.nor0 = Input[0].Nor * vecNor;\n"
"   nor3.nor1 = Input[1].Nor * vecNor;\n"
"   nor3.nor2 = Input[2].Nor * vecNor;\n"
"   return nor3;\n"
"}\n"
//**************************************前がDS*************************************************//
"[maxvertexcount(3)]\n"
"void GS_Before_ds(triangle GS_Mesh_INPUT Input[3], inout TriangleStream <DXR_INPUT> triStream)\n"
"{\n"
"	DXR_INPUT p = (DXR_INPUT)0;\n"

"   Normal3 n3 = NormalRecalculation(Input);\n"

"   p.Pos = Input[0].Pos.xyz;\n"
"   p.Nor = n3.nor0;\n"
"   p.Tex0 = Input[0].Tex0;\n"
"   p.Tex1 = Input[0].Tex1;\n"
"   triStream.Append(p);\n"
"   p.Pos = Input[1].Pos.xyz;\n"
"   p.Nor = n3.nor1;\n"
"   p.Tex0 = Input[1].Tex0;\n"
"   p.Tex1 = Input[1].Tex1;\n"
"   triStream.Append(p);\n"
"   p.Pos = Input[2].Pos.xyz;\n"
"   p.Nor = n3.nor2;\n"
"   p.Tex0 = Input[2].Tex0;\n"
"   p.Tex1 = Input[2].Tex1;\n"
"   triStream.Append(p);\n"
"	triStream.RestartStrip();\n"
"}\n";
//**************************************前がDS*************************************************//
